// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wheycpsmindfvvjinwnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoZXljcHNtaW5kZnZ2amlud256Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MjAzMTMsImV4cCI6MjA2Nzk5NjMxM30.Dm8xOmosnqFXNfLQJxbgJ0GXRO3Yiy5jFzysqwSPfbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});